name: generate animation
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
    - master

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=#00FFFF&color_dots=#0d1117,#0a3d3d,#0e6363,#12a3a3,#00ffff
            dist/github-contribution-grid-snake-dark.svg?color_snake=#00FFFF&color_dots=#0d1117,#0a3d3d,#0e6363,#12a3a3,#00ffff

      - name: push github-contribution-grid-snake.svg to the output branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: ./dist
